#+title: Alacritty :tangle alacritty.yml
#+AUTHOR: S.D
#+PROPERTY: header-args :tangle alacritty.yml
#+auto_tangle: t


* Table of Content :toc:
- [[#window][Window]]
  -  [[#dimensions][Dimensions]]
  - [[#padding][Padding]]
  - [[#opacity][Opacity]]
  - [[#startup-mode][Startup mode]]
  - [[#title][Title]]
- [[#scrolling][Scrolling]]
  -  [[#history][History]]
  - [[#scrolling-speed][Scrolling speed]]
- [[#font-configuration][Font configuration]]
  - [[#font-decoration][Font Decoration]]
- [[#colors][Colors]]
  -  [[#monokai-dark-theme][Monokai dark theme]]
  -  [[#eighties-dark-color-theme][Eighties dark color theme]]
  - [[#atelierheath-theme][Atelierheath theme]]

* Window
Window specifications
**  Dimensions
window dimensions
#+BEGIN_SRC yml :tangle alacritty.yml
window:
  dimensions:
    columns: 80
    lines: 20

#+END_SRC
** Padding
Window padding
#+BEGIN_SRC yml :tangle alacritty.yml
  padding:
    x: 5
    y: 5

#+END_SRC
** Opacity
  Background opacity
#+BEGIN_SRC yml :tangle alacritty.yml
  opacity: 0.8

#+END_SRC
** Startup mode
   Values for `startup_mode`:
     - Windowed
     - Maximized
     - Fullscreen
#+BEGIN_SRC yml :tangle alacritty.yml
  startup_mode: Windowed

#+END_SRC
** Title
   Allow terminal applications to change Alacritty's window title.
#+BEGIN_SRC yml :tangle alacritty.yml
  title: Alacritty
  dynamic_title: true

#+END_SRC
* Scrolling
**  History
  Maximum number of lines in the scrollback buffer.
  Specifying '0' will disable scrolling.
#+BEGIN_SRC yml :tangle alacritty.yml
scrolling:
  history: 10000
#+END_SRC
** Scrolling speed
  Scrolling distance multiplier.
#+BEGIN_SRC yml :tangle alacritty.yml
  multiplier: 3

#+END_SRC
* Font configuration
*** Font
#+BEGIN_SRC yml :tangle alacritty.yml
  normal:
    family: Ubuntu Mono
    style: Regular

  bold:
    family: Ubuntu Mono
    style: Bold

  italic:
    family: Ubuntu Mono
    style: Italic

  bold_italic:
    family: Ubuntu Mono
    style: Bold Italic
#+END_SRC
*** Font Size
#+BEGIN_SRC yml :tangle alacritty.yml
  size: 12.0
#+END_SRC
** Font Decoration
#+BEGIN_SRC yml :tangle alacritty.yml
draw_bold_text_with_bright_colors: true

#+END_SRC
* Colors

**  Monokai dark theme

colors:
  # Default colors
  primary:
    background: '0x272822'
    foreground: '0xf8f8f2'

  # Normal colors
  normal:
    black:   '0x272822'
    red:     '0xf92672'
    green:   '0xa6e22e'
    yellow:  '0xf4bf75'
    blue:    '0x66d9ef'
    magenta: '0xae81ff'
    cyan:    '0xa1efe4'
    white:   '0xf8f8f2'

  # Bright colors
  bright:
    black:   '0x75715e'
    red:     '0xf92672'
    green:   '0xa6e22e'
    yellow:  '0xf4bf75'
    blue:    '0x66d9ef'
    magenta: '0xae81ff'
    cyan:    '0xa1efe4'
    white:   '0xf9f8f5'

**  Eighties dark color theme

colors:
  # Default colors
  primary:
    background: '0x2d2d2d'
    foreground: '0xd3d0c8'

  # Normal colors
  normal:
    black:   '0x2d2d2d'
    red:     '0xf2777a'
    green:   '0x99cc99'
    yellow:  '0xffcc66'
    blue:    '0x6699cc'
    magenta: '0xcc99cc'
    cyan:    '0x66cccc'
    white:   '0xd3d0c8'

  # Bright colors
  bright:
    black:   '0x747369'
    red:     '0xf2777a'
    green:   '0x99cc99'
    yellow:  '0xffcc66'
    blue:    '0x6699cc'
    magenta: '0xcc99cc'
    cyan:    '0x66cccc'
    white:   '0xf2f0ec'

** Atelierheath theme
#+BEGIN_SRC yml :tangle alacritty.yml

colors:
  # Default colors
  primary:
    background: '0x1b181b'
    foreground: '0xab9bab'

  # Normal colors
  normal:
    black:   '0x1b181b'
    red:     '0xca402b'
    green:   '0x379a37'
    yellow:  '0xbb8a35'
    blue:    '0x516aec'
    magenta: '0x7b59c0'
    cyan:    '0x159393'
    white:   '0xab9bab'

  # Bright colors
  bright:
    black:   '0x776977'
    red:     '0xca402b'
    green:   '0x379a37'
    yellow:  '0xbb8a35'
    blue:    '0x516aec'
    magenta: '0x7b59c0'
    cyan:    '0x159393'
    white:   '0xf7f3f7'
#+END_SRC
